#!/usr/bin/bash

# Initialise directories
DATA_DIR_FULL_CADENCE="./data/messenger/full_cadence/"
DATA_DIR_1S="./data/messenger/one_minute_avg/"
mkdir -p $DATA_DIR_FULL_CADENCE
mkdir -p $DATA_DIR_1S

mkdir -p "./data/reduced"
mkdir -p "./data/metrics"
mkdir -p "./data/model"

# Make metakernel
./scripts/make_messenger_metakernel

# Unfortunately the Philpott+ (2020) crossing list cannot be automatically downloaded at this time.

# Download raw data from PDS
echo "Downloading MESSENGER MAG data from PDS-PPI"
echo "Download 1 second average data"
DATA_URL="https://pds-ppi.igpp.ucla.edu/data/mess-mag-calibrated/data/mso-avg/"
DATA_DIR=$DATA_DIR_1S
wget -r -q --show-progress -np -nH -nd -A '*01_V08.TAB' -P $DATA_DIR "$DATA_URL/2011/"
wget -r -q --show-progress -np -nH -nd -A '*01_V08.TAB' -P $DATA_DIR "$DATA_URL/2012/"
wget -r -q --show-progress -np -nH -nd -A '*01_V08.TAB' -P $DATA_DIR "$DATA_URL/2013/"
wget -r -q --show-progress -np -nH -nd -A '*01_V08.TAB' -P $DATA_DIR "$DATA_URL/2014/"
wget -r -q --show-progress -np -nH -nd -A '*01_V08.TAB' -P $DATA_DIR "$DATA_URL/2015/"

echo "Download full cadence data"
DATA_URL="https://pds-ppi.igpp.ucla.edu/data/mess-mag-calibrated/data/mso/"
DATA_DIR=$DATA_DIR_FULL_CADENCE
wget -r -q --show-progress -np -nH -nd -A '*.TAB' -P $DATA_DIR "$DATA_URL/2011/"
wget -r -q --show-progress -np -nH -nd -A '*.TAB' -P $DATA_DIR "$DATA_URL/2012/"
wget -r -q --show-progress -np -nH -nd -A '*.TAB' -P $DATA_DIR "$DATA_URL/2013/"
wget -r -q --show-progress -np -nH -nd -A '*.TAB' -P $DATA_DIR "$DATA_URL/2014/"
wget -r -q --show-progress -np -nH -nd -A '*.TAB' -P $DATA_DIR "$DATA_URL/2015/"
